name: AAPS CI

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Secrets
        run: |
          echo "🔍 Checking required secrets..."
          required_secrets=(
            "KEYSTORE_BASE64"
            "KEYSTORE_PASSWORD"
            "KEY_ALIAS"
            "KEY_PASSWORD"
          )
          missing=0
          for secret in "${required_secrets[@]}"; do
            if [ -z "${!secret}" ]; then
              echo "❌ Missing secret: $secret"
              missing=1
            fi
          done
          if [ $missing -eq 1 ]; then
            echo "❌ Missing required secrets. Stopping build."
            exit 1
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/keystore.jks

      - name: Build AAPS
        run: ./gradlew assembleFullRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-full-release-signed
          path: app/build/outputs/apk/full/release/app-full-release.apk
